version: '3'

tasks:
  build:
    cmds:
      - odin build tree-walk -vet -out:bin/olox-tree-walk

  run:
    deps: [build]
    cmds:
      - ./bin/olox-tree-walk {{.CLI_ARGS}}

  test:
    cmds:
      - odin test test -vet -all-packages -out:bin/test.bin


