version: '3'

tasks:
  build:
    cmds:
      - odin build tree-walk -vet -out:bin/olox-tree-walk

  run:
    deps: [build]
    cmds:
      - ./bin/olox-tree-walk

  test:
    cmds:
      - odin test test/ -vet -all-packages -out:bin/test.bin -define:ODIN_TEST_FANCY=false


